services:
  spring-api-image:
    image: perritoscut
    container_name: contenedor-cut-spring
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    ports:
      - "3307:3306"
    networks:
      - spring-network
    environment:
      - MYSQL_ROOT_PASSWORD=sasa
      - MYSQL_DATABASE=cut
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
networks:
  spring-network:

