spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/cut
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    hikari:
      username: ${DB_USER_NAME}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update

  api:
        security:
          secret: ${JWT_SECRET:123456}

